### ISSUE TITLE
Why special treatment to last iteration of routing algo?

### ISSUE THREAD

**Issue by udion** [danielhavir/capsule-network#2]
I was wondering why you have kept the last iteration of the the routing algo outside the loop and not making the updates, please share your thoughts.

**Comment by danielhavir** [comment]
The main reason is to save compute because the routing algo returns the squashed vector `v` (Procedure 1, line 6, in the paper). Therefore, you don't need to calculate/update the routing weights `b` during the last iteration since that would be redundant (you don't need it) and the weights are initialized to zeros every run anyway. (i.e. Procedure 1, line 7 is not necessary for the *last* iteration). This saves one matrix multiplication.

Also, notice that for the first `num_routing - 1` iterations I calculate the routing weight on a detached tensor `u_hat` to prevent from gradients flow. But the last iteration is done on the original `u_hat` (which is still attached to the graph).

Hope that answers your question.
